#include <assert.h>
#include <string.h>
#define URLROUTER_IMPLEMENTATION
#define URLROUTER_IO
#include "urlrouter.h"

int main(void)
{
	char data[2048];
	urlrouter router;
	urlrouter_init(&router, data, 2048);
	assert(urlrouter_add(&router, "/a/b/c", "/a/b/c") > 0);
	urlrouter_print(&router);
	assert(urlrouter_add(&router, "/a/b/c/e/ef", "/a/b/c/e/ef") > 0);
	urlrouter_print(&router);
	assert(urlrouter_add(&router, "/blabl", "/blabl") > 0);
	urlrouter_print(&router);
	assert(urlrouter_add(&router, "/blabl/7", "/blabl/7") > 0);
	assert(urlrouter_add(&router, "/blabl/14", (void *)1) > 0);
	assert(urlrouter_add(&router, "/blabl/14", (void *)1) == URLROUTER_ERR_PATH_EXISTS);
	urlrouter_print(&router);
	assert(urlrouter_add(&router, "/blabl/28", (void *)1) > 0);
	assert(urlrouter_add(&router, "/route1", (void *)1) > 0);
	urlrouter_print(&router);
	assert(urlrouter_add(&router, "/route2", (void *)1) > 0);
	urlrouter_print(&router);
	assert(urlrouter_add(&router, "/a/b/c/3", (void *)1) > 0);
	assert(urlrouter_add(&router, "/route7", "/route7") > 0);
	assert(urlrouter_add(&router, "/a/b/c/e/5", (void *)1) > 0);
	assert(urlrouter_add(&router, "/a/b/c/6", (void *)1) > 0);
	assert(urlrouter_add(&router, "/blabl/713", (void *)1) > 0);
	assert(urlrouter_add(&router, "/route8", (void *)1) > 0);
	assert(urlrouter_add(&router, "/a/b/c/9", (void *)1) > 0);
	assert(urlrouter_add(&router, "/a/b/c/e/10", (void *)1) > 0);
	assert(urlrouter_add(&router, "/route11", (void *)1) > 0);
	assert(urlrouter_add(&router, "/a/b/c/12", (void *)1) > 0);
	assert(urlrouter_add(&router, "/route13", "/route13") > 0);
	printf("%ld\n", urlrouter_add(&router, "/route43", (void *)1));
	printf("%ld\n", urlrouter_add(&router, "/roaute43", (void *)1));
	urlrouter_print(&router);

	assert(urlrouter_find(&router, "/route13") == "/route13");
	assert(urlrouter_find(&router, "/route7") == "/route7");
	assert(urlrouter_find(&router, "/blabl/7") == "/blabl/7");
	// assert(urlrouter_add(&router, "/blabl/14", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/15", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route16", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route17", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/18", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route19", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/20", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/21", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route22", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route23", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/24", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/25", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route26", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/27", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/28", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route29", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/30", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route31", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route32", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/33", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route34", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/35", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/36", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route37", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route38", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/39", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/40", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route41", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/42", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route43", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route44", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/45", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route46", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route47", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/48", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/49", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/50", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/51", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route52", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route53", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/54", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/55", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/56", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/57", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route58", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route59", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/60", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route61", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route62", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/63", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route64", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/65", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/66", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route67", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route68", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/69", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/70", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route71", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/72", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route73", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route74", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/75", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route76", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/77", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/78", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route79", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/80", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/81", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route82", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route83", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/84", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/85", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route86", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/87", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route88", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route89", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/90", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/91", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route92", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/93", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route94", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/95", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/96", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route97", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/98", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/99", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/100", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route101", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/102", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route103", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route104", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/105", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route106", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route107", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/108", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route109", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/110", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/111", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/112", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route113", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/114", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/115", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route116", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/117", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route118", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/119", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/120", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route121", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route122", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/123", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route124", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/125", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/126", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route127", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route128", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/129", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/130", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route131", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/132", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/133", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route134", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/135", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route136", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route137", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/138", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route139", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/140", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/141", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route142", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route143", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/144", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/145", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route146", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/147", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route148", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route149", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/150", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route151", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route152", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/153", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/154", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/155", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/156", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route157", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route158", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/159", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/160", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/161", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/162", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route163", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route164", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/165", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route166", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route167", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/168", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route169", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/170", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/171", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route172", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route173", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/174", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/175", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route176", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/177", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route178", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route179", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/180", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route181", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/182", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/183", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route184", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/185", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/186", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route187", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route188", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/189", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/190", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route191", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/192", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route193", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route194", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/195", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/blabl/196", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route197", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/198", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/route199", (void *)1) > 0);
	// assert(urlrouter_add(&router, "/a/b/c/e/200", (void *)1) > 0);
	urlrouter_print(&router);
	return 0;
}